=== ashiPerw97/Assignment0/movies.xsd
<?xml version="1.0" encoding= "UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
<xs:element name="movies">
  <xs:complexType>
	<xs:sequence>
		<xs:element name="movie" minOccurs="1" maxOccurs="unbounded">
		  <xs:complexType>
			  <xs:sequence>
			      <xs:element name="title" type="xs:string"/>
				  <xs:element name="year">
					<xs:simpleType>
					  <xs:restriction base="xs:integer">
						<xs:pattern value="\d{4}"/>
					  </xs:restriction>
					</xs:simpleType>
				  </xs:element>
				  <xs:element name="genre">
					<xs:simpleType>
					  <xs:restriction base="xs:string">
					  <xs:enumeration value="action"/>
					  <xs:enumeration value="adventure"/>
					  <xs:enumeration value="comedy"/>
					  <xs:enumeration value="drama"/>
					  <xs:enumeration value="fantasy"/>
					  <xs:enumeration value="horror"/>
					  <xs:enumeration value="mystery"/>
					  <xs:enumeration value="thriller" />
					  <xs:enumeration value="western"/>
				      </xs:restriction>
				    </xs:simpleType>
				  </xs:element>
			  </xs:sequence>
		  </xs:complexType>
		</xs:element>
				
		<xs:element name="actors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="actor" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name" minOccurs="1" maxOccurs="1" />
                          <xs:element type="xs:date" name="DateOfBirth"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
</xs:schema>

=== ashiPerw97/Assignment0/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	    xsi:noNamespaceSchemaLocation="movies.xsd">
	
	<movie> 
		<title>Taken</title> 
		<year>2009</year> 
		<genre>action</genre> 
	</movie>
	<actors> 
		<actor>
			<name>Liam Neeson</name> 
			<dateOfBirth>1952-07-07</dateOfBirth> 
		<actor>
		
		<actor>
			<name>Maggie Grace</name> 
			<dateOfBirth>1983-09-05</dateOfBirth> 
		<actor>
	</actors> 
	
	<movie> 
		<title>New Movie</title> 
		<year>2018</year> 
		<genre>comedy</genre> 
	</movie>
	<actors> 
		<actor>
			<name>Shawn McCarthy</name> 
			<dateOfBirth>2018-02-05</dateOfBirth> 
		<actor>
		
		<actor>
			<name>Taylor Daly</name> 
			<dateOfBirth>2018-02-05</dateOfBirth> 
		<actor>
	</actors> 
	
	
</movies>
